AWSTemplateFormatVersion: 2010-09-09
Description: |
  Template to deploy Roman Numerals Flask App
  
#Parameters:
  
Resources:

  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      GroupName: AllowSSHandHTTP
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
            - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
      Tags: 
        - Key: Name
          Value: RomanNumeralSG

  rWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: String
      InstanceType: String
      KeyName: String
      SecurityGroupIds: 
        - String
      Tags: 
        - Key: Name
          Value: samil-roman-numeral-web-server
      UserData: String 
  
#Outputs: